FEDERATION_SERVER="https://api.stellar.org/federation" 

ACCOUNTS=["", 
""
] 

[DOCUMENTATION] 
ORG_NAME="Investor Pembuatan Online" 
ORG_URL="https://investor.pembuatan.online" 
ORG_LOGO="https://investor.pembuatan.online/logo.png" 

[[CURRENCIES]] 
code="INVEST" 
issuer="" 
status="live" 
name="INVEST" 
desc="There will be only 1,000,000 INVEST existed on SDEX for investors which will generate dividends as much as 2.5% per month for 10 years. The dividends send regularly to investor wallets every month." 
display_decimals=2 
image="https://investor.pembuatan.online/logo.png" 
